/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./public/index.html', './src/**/*.{js,jsx,ts,tsx,html}'],
	theme: {
		extend: {
			colors: {
				Illusion: '#F291D0',
				CeruleanBlue: '#323AD9',
				CaribbeanGreen: '#04D99D',
				ButterCup: '#F2B90C',
				Trinidad: '#F24405',
				CornFlowerBlue: '#417CF2',
				CornFlowerBlueLight: '#6393F2',
				Portica: '#F2E963',
				Tacha: '#D9C359',
				Carnation: '#F26363',
				CatskillWhite: '#f8fafc',
				FrenchRose: '#EF476F',
				Tarawera: '#073B4C',
				BlueChill: '#118AB2',
				GoldenTainoi: '#FFD166',
				Deco: '#D4E09B',
				AppleBlossom: '#A44A3F',
				EbonyClay: '#202C39',
				NewOrleans: '#F2D492',
				Sandybrown: '#F29559',
				RoseFog: '#DFB2AC',
				PickledBluewood: '#283845',
				DarkVanilla: '#D6B39F',
				PowderAsh: '#B4C5C0',
				DoubleSpanishWhite: '#E5D4B5',
				Dallas: '#6B4B20',
				Whiskey: '#D0AA69',
				BlackOlive: '#172310',
				Panache: '#f9fcf8',
				SwansDown: '#e3f2ec',
				Plantation: '#2b5f4b',
				SilverChalice: '#B0B0B0',
				WoodSmoke: '#101214',
				'text-l': '#021d22',
				'background-l': '#fafeff',
				'primary-l': '#d1280a',
				'secondary-l': '#c8f5fc',
				'accent-l': '#ee2e0c',
				"text-d": '#fafeff',
				"background-d": '#021d22',
				"primary-d": '#d1280a',
				"secondary-d": '#02242a',
				"accent-d": '#faa899',
			},
			screens: {
				xs: '480px',
				ss: '620px',
				sm: '768px',
				md: '1060px',
				lg: '1200px',
				xl: '1700px',
			},
			fontSize: {
				fonts: '1rem',
				fontm: '1.5rem',
				fontl: '2rem',
				fontxl: '2.5rem',
				heading: '5rem',
				subheading: '3rem',
				display: '8rem',
				nav: '2rem',
			},
			fontFamily: {
				Nunito: ['Nunito Sans', 'sans-serif'],
				RobotoSlab: ['Roboto Slab', 'serif'],
				RobotoMono: ['Roboto Mono', 'monospace'],
				AbrilFatFace: ['Abril Fatface', 'cursive'],
				Staatliches: ['Staatliches', 'cursive'],
				Unbounded: ['Unbounded', 'cursive'],
				PlayFair: ['Playfair Display', 'serif'],
				NotoSerif: ['Noto Serif', 'serif'],
				Inter: ['Inter', 'sans-serif'],
				OpenSans: ['Open Sans', 'sans-serif'],
			},
			boxShadow: {
				nav: '20px solid #000',
			},
		},
	},
	plugins: [require('prettier-plugin-tailwindcss')],
};
