/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./public/index.html', './src/**/*.{js,jsx,ts,tsx,html}'],
	theme: {
		extend: {
			colors: {
				CatskillWhite: '#f8fafc',
				FrenchRose: '#EF476F',
				Tarawera: '#073B4C',
				BlueChill: '#118AB2',
				GoldenTainoi: '#FFD166',
				Deco: '#D4E09B',
				AppleBlossom: '#A44A3F',
				EbonyClay: '#202C39',
				NewOrleans: '#F2D492',
				Sandybrown: '#F29559',
				RoseFog: '#DFB2AC',
				PickledBluewood: '#283845',
				DarkVanilla: '#D6B39F',
				PowderAsh: '#B4C5C0',
				DoubleSpanishWhite: '#E5D4B5',
				Dallas: '#6B4B20',
				Whiskey: '#D0AA69',
				BlackOlive: '#172310',
				Panache: '#f9fcf8',
				SwansDown: '#e3f2ec',
				Plantation: '#2b5f4b',
				SilverChalice: '#B0B0B0',
				WoodSmoke: '#101214',
				'text-l': '#0c0305',
				'background-l': '#f6dfe2',
				'primary-l': '#5ad3c1',
				'secondary-l': '#c7cdf0',
				'accent-l': '#31b9a5',
				'text-d': '#fafafa',
				'background-d': '#050505',
				'primary-d': '#5ad3c1',
				'secondary-d': '#0b0f28',
				'accent-d': '#86dfd2',
			},
			screens: {
				xs: '480px',
				ss: '620px',
				sm: '768px',
				md: '1060px',
				lg: '1200px',
				xl: '1700px',
			},
			fontSize: {
				fonts: '1rem',
				fontm: '1.5rem',
				fontl: '2rem',
				fontxl: '2.5rem',
				heading: '5rem',
				subheading: '3rem',
				display: '8rem',
				nav: '2rem',
			},
			fontFamily: {
				sans: ['Nunito Sans', 'sans-serif'],
				serif: ['Roboto Slab', 'serif'],
				mono: ['Roboto Mono', 'monospace'],
				display: ['Abril Fatface', 'cursive'],
			},
		},
	},
	plugins: [require('prettier-plugin-tailwindcss')],
};
